### ISSUE TITLE
do not work sub menu in depth 3

### ISSUE THREAD

**Issue by mdabbagh-ir** [AlexWebLab/bootstrap-5-wordpress-navbar-walker#16] opened 2021-08-05 15:35 UTC
do not work sub menu in depth 3.
what's the solution?

**Comment by 24Degrees** [comment] 2021-08-05 18:35
Bootstrap 5 does not work beyond depth 1. 

Michaël Martens
24degrees

**Comment by mdabbagh-ir** [comment] 2021-08-05 19:13
Thanks for the prompt response
How do I change the nav-walker so that the output of the level 3 menu is as follows?

<ul class="navbar-nav mb-lg-0 fs-6 flex-grow-1">
    <li class="nav-item ms-3">
        <a class="nav-link " href="#">home</a>
    </li>
    <li class="nav-item dropdown ms-3">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">categorys</a>
        <ul class="dropdown-menu dropdown-menu-right menu1" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item dropdown-toggle" href="#">frontend</a>
            <ul class="dropdown-menu menu2 dropdown-menu-right">
                <li><a class="dropdown-item ps-4" href="#">html</a></li>
                <li><a class="dropdown-item ps-4" href="#">css</a></li>
            </ul>
            <a class="dropdown-item dropdown-toggle" href="#">backend</a>
            <ul class="dropdown-menu menu2 dropdown-menu-right">
                <li><a class="dropdown-item ps-4" href="#">php</a></li>
                <li><a class="dropdown-item ps-4" href="#">nodejs</a></li>
            </ul>
        </ul>
    </li>
</ul>

**Comment by mdabbagh-ir** [comment] 2021-08-05 19:14
Thanks for the prompt response
How do I change the nav-walker so that the output of the level 3 menu is as follows?

<ul class="navbar-nav mb-lg-0 fs-6 flex-grow-1">
    <li class="nav-item ms-3">
        <a class="nav-link " href="#">home</a>
    </li>
    <li class="nav-item dropdown ms-3">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">categorys</a>
        <ul class="dropdown-menu dropdown-menu-right menu1" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item dropdown-toggle" href="#">frontend</a>
            <ul class="dropdown-menu menu2 dropdown-menu-right">
                <li><a class="dropdown-item ps-4" href="#">html</a></li>
                <li><a class="dropdown-item ps-4" href="#">css</a></li>
            </ul>
            <a class="dropdown-item dropdown-toggle" href="#">backend</a>
            <ul class="dropdown-menu menu2 dropdown-menu-right">
                <li><a class="dropdown-item ps-4" href="#">php</a></li>
                <li><a class="dropdown-item ps-4" href="#">nodejs</a></li>
            </ul>
        </ul>
    </li>
</ul>

**Comment by AlexWebLab** [comment] 2021-08-06 03:36
I keep open this issue in case people want to contribute to this. In any case, it won't be merged to the main branch because I want to keep this nav walker strictly compatible with Bootstrap 5.

**Comment by paulswanson** [comment] 2021-09-23 06:16
Anyone got a solution to this? Or, at least some idea where to root of the problem is?

**Comment by crftwrk** [comment] 2021-09-23 07:33
Try this https://bootstrap-menu.com

**Comment by AlexWebLab** [comment] 2021-09-23 09:12
Bootstrap 5 doesn't support level 3 (even if you can create infinite levels with the WordPress menu).

**Closed by AlexWebLab** 2021-09-23 09:12 UTC

**Comment by paulswanson** [comment] 2021-09-23 09:57
> Bootstrap 5 doesn't support level 3 (even if you can create infinite levels with the WordPress menu).

OK. Others might find it helpful if this limitation is outlined in the README.md.

**Comment by paulswanson** [comment] 2021-09-23 10:02
> Try this https://bootstrap-menu.com

Yeah, I've also got this, it works great and has good doco. Still needs a custom Walker_Nav_Menu for WP integration.
